//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 請假細項
    {
        public int EmployeeID { get; set; }
        public string 部門 { get; set; }
        public string 請假類別 { get; set; }
        public string 請假班別 { get; set; }
        public string 請假時數 { get; set; }
        public string 開始日期 { get; set; }
        public string 結束日期 { get; set; }
        public string 申請時間 { get; set; }
        public string 代理人 { get; set; }
        public string 審核狀態 { get; set; }
    }
}
